# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: YAO-CHEN CHI
title: B.S.E. in Electrical Engineering, National Cheng Kung University (NCKU)
email: jason871110@gmail.com
website: https://jason871110.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jason871110
github_username: jason871110
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tzjnn
linkedin_username: yao-chen-chi-670ab3179
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: jason871110
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ii  
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Cheng Kung University
        caption: 2017 - 2021 
        sub_title: BSc Electrical Engineering
        quote: >
         One of the top university in Taiwan.
        description: | # this will include new lines to allow paragraphs
          - Last 60 GPA: **4.25/4.3**
          - Cumulative GPA: 3.74/4.3
          - Dean's List Award(top 5% of the class)

                Ranked 1 out of 55 in Spring 2021 semester.
                Ranked 2 out of 55 in Fall 2020 semester.
                Ranked 3 out of 55 in Spring 2020 semester.
          - Fellowship, National Science Concil: One of 8 students out of 162 in NCKU Department of Electrical Engineering that won the fellowship.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:  Optimization for Content-Centric Networking
        description: |
          - Implementing Content-Centric Networking on Python by **Multithreaded Programming** 
          - Optimized the cache hit ratio by setup priority queue and SDN characteristic to the network **(Highest cache hit ratio in class)**
           
      - layout: top-middle
        title: Road Doctor
        description: |
          - Proposed an automated **mobile-based (Android)** road condition monitoring system
          - Used **Fast Fourier Transform (FFT) and Band-pass filter** to filter the noise in the collecting data, then employed **“XGBoost”** as the primary model to classify potholes from collecting data **with 0.985 accuracy** 
          
      - layout: top-middle
        title: Machine Learning for Stock Trading  
      
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - Referred to a paper posted on ICAIF 2020 about deep reinforcement learning for automated stock trading
          - Proposed a deep reinforcement ensemble trading method based on the combination of **Deep Deterministic Policy Gradient (DDPG) and Advantage Actor-Critic(A2C)**, which increased cumulative return from **70.4% to 121% from Jan 2016 to May 2020 and increased Sharpe Ration from 1.30 to 1.61** compared to the approach from original method (Best final presentation in class) 
      - layout: top-middle
        title: Optimization of Hyperplane-based Craig-simplex-identification Algorithm & Improvement for Hyperspectral Inpainting Method
        description: |
          - Developed algorithm that takes **only 50% of time** compared to the original algorithm **(Fattest in class)**
          
      - layout: top-middle
        title: Smart K
        description: |
          - Used **Raspberry Pi, Arduino, sensors, relays, and infrared transmitter** to control the **light and air-conditioner** in the classroom
          - Implemented **Yolov3 through darknet** structure on Raspberry Pi to check for students in classroom
           
      - layout:  top-middle
        title: Fingerprint Boosting Scooter   
        description: | # this will include new lines to allow paragraphs
          - Used Arduino, fingerprint module, and other electronic parts to transform my normal scooter into fingerprint boosting scooter 
  
  - title: Awards and Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Third Place, Online Research Day, NCKU College of Electrical Engineering & Computer Science 
        description: |
          - Received for ranking 3 out of 270 students from NCKU College of Electrical Engineering & Computer Science.(June 2021)     
      
      - layout: top-middle
        title: Scholarship, Cathay United Bank
        description: |
          - Received for my outstanding academic performance.(May 2020;May 2021).  
      
      - layout: top-middle
        title: First Place, Undergraduate Research
        description: |
          - Won in Computer and COmmunication track.(Apr 2020)
      
      - layout: top-middle
        title: High Distinction Award of Cross-disciplinary Final Presentation
        description: |
          - Earned for ranking 1st out of 30 teams in Foresight Talent Cultivation Program (Jan 2021)
      - layout: top-middle
        title: Qualcomm Special Award, MOBILEHERO Competition-Internet of Things Track
        description: |
          - Received for being in top 5 of 492 teams.(Nov 2020)
      - layout: top-middle
        title: Best Summer Intern Award, AU Optronics Corporation      
        description: |
          - Received for ranking 1 out of 90 interns.(Aug 2019)
      - layout: top-middle
        title: Honorable Mention Award, National Open-source Software Design Competition 
        description: |
          - Earned for ranking 4 out of 50 teams.(Dec 2018) 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SUN ENGINE Solar Corp (startup)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Embedded Software Engineer
        caption: June 2020 - Sept 2020
        quote: >
          Providing solution to Intelligent Logistics.
        description: | # this will include new lines to allow paragraphs
          - Cooperated with logistics company to construct part of intelligent logistics tracking system.
          - Used Raspberry Pi as edge data center to collect temperature, GPS location, and video signal on trucks and develop API for server to access these data.
          - Decreased cost of data monitoring for trucks by about 40%.
      - layout: left
        title: NCKU
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: Dec 2019 - Feb 2020
        quote: >
          Develop experimental devices for Smart Design Lab.
        description: | # this will include new lines to allow paragraphs
          - Implemented transcutaneous electrical nerve stimulator by Arduino and circuit to make it possible to change stimulant current into small scale, such as 5 mA or 1 mA, and have a user-friendly UI to choose frequency and current scale on computer.
          - Integrated motors, computers, and Arduinos to form a multi-motor vibrating system to conduct experiment and discover how elderly people react to stimulation generated by system.
      - layout: left
        title: AU Optronics Corporation
        link: https://www.auo.com/en-global
        # link_text: boringcompany.com
        sub_title: Software Engineer, Intern 
        caption: July 2019 - Aug 2019
        quote: >
          Develop DAQ system for fab.
        description: | # this will include new lines to allow paragraphs
          - Integrated PLCs, current sensors, vibrating sensors, and microcomputers to set up a high-frequency data acquisition system for machine in Fab, which reduced price of DAQ system by about 75%.
          - Created service to provide real-time data about machine, reducing 90% of time to check machine status. 
      - layout: left
        title: SKRABUR (startup)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: Feb 2019 - June 2020
        quote: >
          Develop experimental devices for Smart Design Lab.
        description: | # this will include new lines to allow paragraphs
          - Cooperated with industrial designer to design a user-friendly order interface for unmanned restaurant.
          - Used Django as backend framework and web-based application for mobile phone. 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cyber-physical system and software engineering some of my other interests and past extracurricular activities are:
   - Runner, NCKU School Track and Field Team 
   - Activity Organizer/Housekeeper, International Hostel, Nanjing, China 
   - Member, Motors Club, NCKU 
   - Member, Rotary Club, NCKU
   - Organizer, Electrical Engineering Summer Camp, NCKU 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
